export const CELEBRITIES = [
  { name: "Taylor Swift", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_4.png" },
  { name: "Elon Musk", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/99/Elon_Musk_Colorado_2022_%28cropped2%29.jpg" },
  { name: "Zendaya", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/28/Zendaya_at_the_2019_MTV_Movie_and_TV_Awards.jpg" },
  { name: "Lionel Messi", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Lionel_Messi_20180626.jpg" },
  { name: "Cristiano Ronaldo", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg" },
  { name: "Ariana Grande", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Ariana_Grande_at_the_2020_Grammy_Awards.jpg" },
  { name: "Bill Gates", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Bill_Gates_2017_%28cropped%29.jpg" },
  { name: "Beyonce", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Beyonc%C3%A9_at_the_2016_MTV_Video_Music_Awards.jpg" },
  { name: "Tom Cruise", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/33/Tom_Cruise_by_Gage_Skidmore_2.jpg" },
  { name: "Rihanna", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Rihanna_at_Crop_Over_2017.jpg" },
  { name: "Dwayne Johnson", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/Dwayne_Johnson_2021.jpg" },
  { name: "Robert Downey Jr", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/Robert_Downey_Jr_2014_Comic_Con_%28cropped%29.jpg" },
  { name: "Brad Pitt", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Brad_Pitt_2019_by_Glenn_Francis.jpg" },
  { name: "Angelina Jolie", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Angelina_Jolie_2_2014.jpg" },
  { name: "Will Smith", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Will_Smith_2017.jpg" },
  { name: "Leonardo DiCaprio", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/25/Leonardo_DiCaprio_2014.jpg" },
  { name: "Scarlett Johansson", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Scarlett_Johansson_by_Gage_Skidmore_2.jpg" },
  { name: "Margot Robbie", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Margot_Robbie_at_the_2023_World_Premiere_of_Barbie.jpg" },
  { name: "Selena Gomez", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/85/Selena_Gomez_at_the_2024_Cannes_Film_Festival.jpg" },
  { name: "Keanu Reeves", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Keanu_Reeves_at_the_2019_Toy_Story_4_Premiere.jpg" },
  { name: "Jennifer Lawrence", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/54/Jennifer_Lawrence_at_the_2015_San_Diego_Comic-Con_International.jpg" },
  { name: "Tom Hanks", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Tom_Hanks_TIFF_2019.jpg" },
  { name: "Meryl Streep", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Meryl_Streep_at_the_Tokyo_International_Film_Festival_2016.jpg" },
  { name: "Jackie Chan", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Jackie_Chan_July_2016.jpg" },
  { name: "Morgan Freeman", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Morgan_Freeman_at_The_Great_Lego_Adventure_Premiere.jpg" },
  { name: "LeBron James", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cf/LeBron_James_crop.jpg" },
  { name: "Serena Williams", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Serena_Williams_at_the_2013_US_Open.jpg" },
  { name: "Shakira", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Shakira_2023_4.png" },
  { name: "Lady Gaga", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Lady_Gaga_at_Premiere_of_A_Star_Is_Born%2C_Toronto.jpg" },
  { name: "Michael Jordan", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg" },
  { name: "Oprah Winfrey", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/da/Oprah_Winfrey_at_the_2011_Governors_Awards.jpg" },
  { name: "Justin Bieber", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/da/Justin_Bieber_in_2020.jpg" },
  { name: "Emma Watson", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Emma_Watson_2013.jpg" },
  { name: "Benedict Cumberbatch", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Benedict_Cumberbatch_2014.jpg" },
  { name: "Chris Hemsworth", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Chris_Hemsworth_by_Gage_Skidmore_2.jpg" },
  { name: "Gal Gadot", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Gal_Gadot_2017_by_Gage_Skidmore.jpg" },
  { name: "Adele", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/52/Adele_2016.jpg" },
  { name: "Bruno Mars", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Bruno_Mars_2017.jpg" }
];

export const GRID_SIZE = 12; // 12x12 grid
export const TOTAL_TILES = GRID_SIZE * GRID_SIZE;
export const REVEAL_INTERVAL_MS = 1500; // reveal a piece every 1.5 seconds
